FROM node:16-alpine AS build
RUN apk add python3
RUN ln -sf /usr/bin/python3 /usr/bin/python
RUN apk add build-base
RUN apk add curl
ENV NODE_ENV=production
WORKDIR /home/node/mining-pool
RUN curl -o mining-pool-latest.tar.gz -L https://api.github.com/repos/alephium/mining-pool/tarball
RUN tar -xf mining-pool-latest.tar.gz && rm mining-pool-latest.tar.gz
RUN cd * && mv ./* ../. && cd ..
RUN npm ci

FROM node:16-alpine AS run

USER node
COPY --from=build /home/node/mining-pool/ /home/node/mining-pool/

USER root
RUN apk add tini
RUN mkdir /home/node/mining-pool/logs && chown node /home/node/mining-pool/logs

USER node
WORKDIR /home/node/mining-pool

ENV NODE_ENV=production

EXPOSE 20032
VOLUME /home/node/mining-pool/logs

ENTRYPOINT ["/sbin/tini","--","npm","run","start"]
